Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os 
os.makedirs('/content/asset')
df.to_csv('/content/asset/news_media_indonesia_sepak_bola.csv')
------------------


[0;31m[0m
[0;31mFileExistsError[0mTraceback (most recent call last)
[0;32m<ipython-input-7-f02b9d3c86ee>[0m in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [0;32mimport[0m [0mos[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mos[0m[0;34m.[0m[0mmakedirs[0m[0;34m([0m[0;34m'/content/asset'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mdf[0m[0;34m.[0m[0mto_csv[0m[0;34m([0m[0;34m'/content/asset/news_media_indonesia_sepak_bola.csv'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.10/os.py[0m in [0;36mmakedirs[0;34m(name, mode, exist_ok)[0m
[1;32m    223[0m             [0;32mreturn[0m[0;34m[0m[0;34m[0m[0m
[1;32m    224[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 225[0;31m         [0mmkdir[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    226[0m     [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    227[0m         [0;31m# Cannot rely on checking for EEXIST, since the operating system[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileExistsError[0m: [Errno 17] File exists: '/content/asset'

